name: Check wxWidgets message catalogs
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '33 3 * * *'
  push:
    branches:
    - main
#  pull_request:
#    branches:
#    - main

jobs:
  Run-Check:
    name: "Run all catalog checks"
    runs-on: [ubuntu-latest]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit
      # and push the added or changed files to the repository.
      contents: write

    steps:
    - name: Install dependencies (Linux)
      run: |
        sudo apt-get update -y
        sudo apt-get install -y gettext

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Check message catalogs, update if necessary
      run: |
        bash --version
        ./scripts/checkwxstd.sh

    - name: Auto commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: 'wxstd/*.pot wxstd/*.po wxstd/*.mo samples/internat/**/*.po samples/internat/**/*.mo'
        commit_message: "[GitHub Action] Update message catalogs"
#        commit_user_name: Firstname Lastname
#        commit_user_email: fn.ln@example.com
#        commit_author: Firstname Lastname <fn.ln@example.com>
